# -*- coding: utf-8 -*-
"""data_manupulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHMrpoSMfQLO0Ayaa5mjxZl0zFUHbOI2
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import  pandas as  pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("billionaires_data_edited.csv")

df.head()

df.isnull().values.any()

df.isnull().sum()

df['Age'].fillna((df['Age'].mean()), inplace=True)

df.isnull().sum()

sns.relplot(x="Rank",y="Net Worth",data=df,height=5,aspect=2)

plt.rcParams["figure.figsize"] = (20,10)
country_cnt = df['Country'].value_counts().to_dict()
countries = list(country_cnt.keys())
cnt = list(country_cnt.values())

ax = sns.barplot(x=countries,y=cnt)
ax.set_title("Country Presence")
ax.set_xticklabels(ax.get_xticklabels(), rotation=90);
ax.set_xticklabels(ax.get_xticklabels(), rotation=90);

plt.rcParams["figure.figsize"] = (20,10)
Industry_cnt = df['Industry'].value_counts().to_dict()
Industries = list(Industry_cnt.keys())
cnt = list(Industry_cnt.values())

ax = sns.barplot(x=Industries,y=cnt)
ax.set_title("Industry Presence")
ax.set_xticklabels(ax.get_xticklabels(), rotation=90);
ax.set_xticklabels(ax.get_xticklabels(), rotation=90);

# Save DataFrame to CSV file
df.to_csv('cleaned_data.csv',index=False)

# Download the CSV file
from google.colab import files
files.download('cleaned_data.csv')